# Article 2: trajectoires de diversité des parcelles

L'un des fondements de l'écologie est est de comprendre les processus qui régissent l'assemblage et la coexistence des espèces en communautés, d'autant plus dans le cas des forêts tropicales pour lesquelles sont de plus débattus l'origine et le maintien de leur extrêmement diversité.
Les hypothèses débattues aujourd'hui invoquent d'une part des processus déterministes, qui sélectionnent les espèces selon leur aptitude dans l'environnement considéré, et d'autre part des processus stochastiques, invoquant les contraintes historiques et de limitation de dispersion ou de croissance.
Ce cadre conceptuel est matérialisé par le débat invoquant la prépondérance des processus stochastiques dans la construction des forêts tropicales [@Hubbell1999] opposé à la théorie des perturbations intermédiaires qui prédit une diversité maximal pour un régime moyen de perturbation par la prépondérence des processus déterministes d'exclusion compétitive et de filtrage des espèces[@Molino2001].
Selon la théorie des perturbations intermédiaires un régime moyen de perturbations modifierait régulièrement mais non drastiquement les conditions environnementales biotiques (interactions entre individus) et abiotiques (ensoleillement, température, flux d'eau et de matière, etc) et permettrait à diverses espèces de s'installer lorsque les conditions leurs sont favorables [@Kariuki2006a;@Berry2008a].
Vraisemblablement les communautés sont déterminées par une combinaison variables de processus stochastiques et déterministes, et la question se porte alors sur les facteurs déterminant leurs importances respectives. 
Identifier les processus déterminant l'assemblage des communautés permet non seulement d'en comprendre le fonctionnement mais également d'en anticiper les dynamiques.
La prépondérance des processus déterministes par exemple implique une correspondance unique entre un environnement et une communauté, quelle que soit son histoire la composition en espèce convergera toujours vers une certaine configuration.
Une plus grand importance des processus stochastiques à l'inverse produira une divergence aléatoire des communautés et maintiendra des configurations différentes dans un environnement homogène.
Les processus déterministes impliquent différemment les espèces et laissent ainsi une signature taxonomique et fonctionnelle dans la structure des communautés [@Funk2017] qui permet d'identifier les processus en jeu et leur importance.

Nous proposons ici d'étudier les trajectoires de diversité et de composition taxonomique et fonctionnelle en forêt tropicale après perturbation pour identifier les processus écologiques déterminants la dynamique des communautés, en interrogeant spécifiquement la validité de la théorie des perturbations intermédiaires, et clarifier les différents aspects de leur résilience.

Ces trajectoires ont mis en évidence la restoration des communautés initiales et le maintien de leurs différences en composition spécifique, mais avec un décalage entre caractéristiques taxonomiques et fonctionnelles. 
Après perturbation les communautés ont suivi une trajectoire fonctionnelle commune, déterminée par l'intensité de la perturbation et validant ainsi la théorie des perturbations intermédiaires.
Les trajectoires taxonomiques en revanche ont prouver dépendre plus de la composition initiale de la communauté que de la perturbation, et ont montré une restoration plus lente du fait de la difficile récupération des espèces rares inféodées aux peuplements matures et exclues par la compétition avec les espèces en place.
Le décalage entre trajectoires fonctionnelle et taxonomique et la faible cohérence taxonomique de la théorie des perturbations intermédiaires s'expliquent par une réorganisation de la redondance fonctionnelle après perturbation.
Cette redondance dans l'espace fonctionnel de la communauté initiale diminue après perturbation suite à la disparition d'arbres et d'espèces, mais l'espace est rapidement réinvestit par les espèces dominantes qui permettent une rapide restoration fonctionnelle. 
La restoration est en revanche plus lente pour les espèces rares qui partagent les même caractéristiques fonctionnelles et sont donc en compétition pour les resources lumineuses.
Les trajectoires des parcelles de Paracou démontrent donc une résilience rapide et commune en termes de fonctionnement mais plus lente en termes de taxonomie et dépendant de la communauté initiale.
La lente restoration de la redondance fonctionnelle démontre un effet persistant des perturbations et interroge fortement la résilience suite à plusieurs perturbations.