# Conclusion et perspectives

La diversité des communautés d'arbres a un rôle central pour le fonctionnement et le maintien des écosystèmes forestiers et des services qu'ils rendent [@Tilman2014].
Expliciter la réponse de cette diversité et en comprendre les mécanismes et les déterminants est incontournable pour anticiper le devenir des forêts dans le contexte actuel et adapter leur gestion et leur conservation [@Barlow2018]. 
Nous examinons dans cette thèse la réponse taxonomique et fonctionnelle d'une communauté d'arbres de forêt Néotropicale après un gradient de perturbation.

Le premier travail de cette thèse a été la mise au point d'une méthode d'estimation fiable de la diversité des communautés à partir des inventaires forestiers.
L'étude de la diversité des forêts tropicales est souvent compromise par la précision limitée des inventaires botaniques et des bases de données fonctionnelles du fait de leur coût financier et humain.
Pour pallier les incertitudes inhérentes aux inventaires et aux bases de données nous avons mis au point un estimateur de diversité taxonomique et fonctionnelle et l'avons testé et calibré à partir d'inventaires réels.
Cet estimateur a ensuite permis de tracer des trajectoires fiables de diversité taxonomiques et fonctionnelles pour les communautés et le recrutement d'une forêt Néotropicale sur 30 ans après un gradient de perturbation. 
Ces trajectoires ont permis de montrer des changements de diversité et de composition taxonomiques des communautés après perturbation.
Conformément à la théorie de sperturbations intermédiaires, au-delà d'un seuil d'intensité le recrutement des pionnières induit une augmentation persistente de l'équitabilité des communautés au détriment des espèces rares de forêt mature.
Par ailleurs les trajectoires ont montré un découplage entre trajectoires taxonomiques et fonctionnelles dû à la diminution de la redondance fonctionnelle après perturbation.
La restauration de la redondance fonctionnelle a montré être le paramètre déterminant de la résilience des communautés, plus lent à retrouver une valeur initiale que la diversité et la composition.
Trente ans après perturbation, la restauration des processus de recrutement, de la composition et de la diversité des communautés reste inachevée mais est visible quelle que soit l'intensité de la perturbation initiale.

Ces résultats conduisent à différentes perspectives vis à vis (i) des processus régissant l'assemblage des espèces en communautés et leurs dynamiques, (ii) des modes de gestion et de conservation durables des forêts tropicales, et (iii) de la modélisation de la diversité des communautés.

## Des communautés régies entre déterminisme et stochasticité

Comprendre la réponse des communautés aux perturbation revient à identifier les processus régissant la coexistence et l'assemblage des espèces.
En forêt tropicale ces processus sont encore débattus.
Spécifiquement le débat porte sur la prépondérance des processus stochastiques par rapport à des processus déterministes favorisant les espèces selon leurs caractéristiques fonctionnelles.
La prépondérance de processus stochastique, supposée par la théorie neutre, implique un assemblage aléatoire des communautés dépendant uniquement de contingences historiques (ordre d'arrivée des espèces, mortalité aléatoire, activité anthropique) ou géographiques (limitation de la dispersion).
La prépondérance de processus déterministes, supposée par la théorie des perturbations intermédiaires, suppose à l'inverse la convergence des communautés vers une composition et une diversité dépendant des caractéristiques environnementales.
Bien que déattues les deux théories neutres et déterministes ne se sont pas incompatibles et peuvent être pertinentes dans différents cas de figure.
Ainsi, la théorie intégrative proposée par @Chave2004 explique-t-elle la diversité et la composition des communautés par une combinaison des processus stochastiques et déterministes variable dans le temps et l'espace.

### Un modèle de succession défini


La perturbation, matérialisée par la mortalité d'une partie de la communauté, modifie en elle-même la distribution d'âge des arbres, la structure de hauteur et de diamètre des communautés et leur environnement abiotique (lumière, flux d'eau et de nutriments) [@Gourlet-Fleury2000;@Putz2012;@Piponiot2016;@Rutishauser2016].
Bien que la mortalité soit plus importante après perturbation, la composition et la diversité des arbres survivants reflète la communauté initiale [@Herault2018].
Les processus de recrutement en revanche se sont montrés en revanche très différents après perturbations.

Les trajectoires de diversité du recrutement ont permis de distinguer trois phases de succession après perturbation, correspondant à différents processus écologiques déterministes et stochastiques.
La réponse des communautés aux perturbations est ainsi déterminée tout d'abord par le recrutement de plantules déjà établies, bénéficiant en premier de l'espace environnemental rendu disponible par la perturbation, puis par le recrutement de pionnières et d'héliophiles favorisées par leurs stratégies d'acquisition de la lumière efficaces, et enfin par le retour progressif aux processus de recrutement initiaux [@Denslow2000;@Herault2010;@Herault2011].

Cette succession est déterminée par l'émergence après perturbation de processus déterministes éclipsant les processus stochastiques, neutres, qui maintiennent la diversité des communautés en forêt non perturbée.
Ces processus déterministes changent la diversité et la composition des individus recrutés et, bien qu'eux-même rapidement restaurés, impactent l'ensemble de la communauté sur plusieurs décennies et dépendent largement de l'intensité de la perturbation et de la composition initiale.

La réponse des communautés aux perturbations est donc définie par une succession de processus déterministes, mais l'impact sur les trajectoirse taxonomiques et fonctionnelles à l'échelle de toute la communauté est plus variable.

### Une succession fonctionnelle déterministe

La réponse des communautés aux perturbations dépend des changements biotiques et abiotiques augmentant la croissance des arbres et le nombre de recrutés.
Après perturbation l'émergence de processus déterministes favorisant les espèces pionnières et héliophiles entraîne une augmentation de la diversité fonctionnelle et un déplacement de la composition fonctionnelle vers des stratégies fonctionnelles d'acquisition et d'utilisation efficaces de la lumière  [@Violle2007b;@Baraloto2012a].

Dans un premier temps le recrutement des juvéniles déjà en place avant perturbation ne modifie pas la diversité et la composition fonctionnelles de la communautée. 
Dans un deuxième temps les arbres recrutés sont issus de la germination des graines de la banque du sol et consituent l'essentiel du recrutement après perturbation [@Lawton1988].
Les espèces pionnières et héliophiles sont alors favorisées au détriment des espèces tolérantes à l'ombre inféodées aux forêts non perturbées.
Ces espèces héliophiles, auparavant rares ou peu fréquentes, deviennent alors communes et leur recrutement augmente la diversité fonctionnelle.
Au delà d'un seuil d'intensité de perturbation (plus de 25% de biomasse initiale perdue) le recutement est dominé par quelques espèces très pionnières (par exemple *Cecropia spp*, *Pourouma spp.* ou *Vismia spp.*) [@Guitet2018].
Il existe cependant un compromis fonctionnel entre les stratégies "acquisitives" et "conservatives" des ressources: les espèces héliophiles présentent une capacité d'acquisition et d'utilisation rapide des ressources mais ont une durée de vie courte [@Falster2011].
La croissance des héliophiles modifie de plus la structure et l'environnement abiotique de la communauté (fermeture de la canopée, rétablissement de la compétition, etc.), si bien que les espèces tolérantes à l'ombre plus commune avant perturbation remplacent les héliophiles après une dizaine d'années [@Denslow2000].
Les caractéristiques fonctionnelles initiales sont donc restaurées dans un troisième temps.
Après perturbation les communautés suivent donc une trajectoire fonctionnelle cyclique et commune à toutes les communautés, déterminée par les caractéristiques fonctionnelles des pionnières et des héliophiles recrutées.
La réponse fonctionnelle des communautés, bien que très informative du fonctionnement des communautés après perturbation, n'est cependant pas le miroir de la réponse taxonomique.
Diversité et composition fonctionnelle ne tiennent en effet pas compte de l'identité des espèces et sont déterminées par les espèces dominantes [@Grime1998;@Lavorel2002].

### Les trajectoires taxonomique

Les trajectoires taxonomiques se sont montrées décorrélées des trajectoires fonctionnelles, dépendantes de l'intensité de perturbation et de la composition de la communauté.
Bien que la composition des communauté soit initialement différentes, les espèces pionnières et héliophiles recrutées après perturbation sont identiques pour toutes les communautés et quelle que soit l'intensité de perturbation.
Les différences de composition sont donc maintenues après perturbation, impliquant que la trajectoire taxonomique après perturbation dépend de la composition initiale.
Peu d'espèces initialement absentes s'installent après perturbation malgré l'espace libéré, du fait probablement des limites de dispersion identifiées pour beaucoup d'espèces de forêt tropicale [@Svenning2005].
Conformément à l'esprit de la théorie neutre la composition taxonomique des communautés relève donc de la contingence historique, *i.e.* du hasard de l'arrivée et de l'installation des espèces, plutôt que de processus de déterministes [@Hubbell2001].

Par ailleurs, conformément aux hypothèses de @Connell1978, le recrutement de pionnières et d'héliophiles augmente la richesse et l'équitabilité des communautés jusqu'à un seuil d'intensité de perturbation (environ 25% de biomasse initiale perdue).
La diversité taxonomique augmente pendant les deux premières phases de la succession, jusqu'à la restauration des processus de recrutement stochastiques: la diversité est maximale quelque temps après une perturbation d'intensité moyenne [@Molino2001:@Guitet2018].
Au delà d'un seuil d'intensité en revanche la favorisation d'espèces nouvelles ou peu communes ne compense pas les disparitions dues à la perturbation.
Les espèces pionnières sont alors dominantes, la richesse taxonomique est diminuée puis restaurée sans dépasser la richesse initiale, et l'équitabilité est durablement augmentée.

Si, comme on l'a vu, les communautés convergent dans l'espace fonctionnel elles divergent dans l'espace taxonomique [@Fukami2005].
Cette dichotomie entre trajectoires taxonomiques et fonctionnelles s'explique par la redondance fonctionnelle.
La redondance fonctionnelle, qui mesure le nombre d'espèces partageant les mêmes charactéristiques fonctionnelles, est élevée en forêt tropicale [@Bellwood2006].
Bien que la composition des communautés soit différente, leurs réponses fonctionnelles aux perturbations peuvent donc être similaires, différentes espèces remplissant un rôle identique.
De plus l'impact fonctionnel des perturbations est atténué, le rôle d'une espèce disparue de la communauté étant assuré par une espèce redondante [@Carmona2016].
Après perturbation, la disparition de certaines espèces diminue la redondance fonctionnelle de la communauté et explique a décorrélation entre trajectoires taxonomiques et fonctionnelles.
La redondance fonctionnelle s'impose comme l'élément clé de la restauration des communautés.
La redondance fonctionnelle garantie la résilience des communautés et atténue l'impact des perturbations sur le fonctionnement des écosystèmes.
Sa restauration est cependant l'élément cinétiquement déterminant de la résilience des communautés: une redondance fonctionnelle élevée implique une compétition importante entre espèces redondantes.
La restauration de la redondance fonctionnelle relève du principe de "lottery recruitment": les premières espèces recrutées s'établiront dans la communauté tandis que celles par hasard recrutées tradivement seront en compétition ave les premières et s'établiront plus difficilement [@Busing2002].
La restauration de la composition taxonomique et de la redondance fonctionnelle initiales sont donc longues et difficiles à anticiper.

On s'attend à ce que la réponse des communautés après de nouvelles pertubations soit assez différente, et notamment à ce que le fonctionnement finisse par être modifié sur le long terme et la redondance fonctionnelle n'est pas restaurée.
La restauration lente des espèces rares quand à elle accroît le risque de voir certaines espèces disparaître localement, et de voir la richesse taxonomique décliner petit à petit.

## Vers une gestion plus durable intégrant la préservation de la biodiversité

L'exploitation sélective est considérée comme étant l'une des pratiques d'exploitation les moins néfastes pour préserver l'intégrité et le fonctionnement des forêts tout en dégageant des bénéfices économiques et sociaux significatifs [@Chaudhary2016].
L'exploitation sélective a été adoptée dernièrement par de nombreux pays, suite à des réorganisations de l'économie locale, en réponse aux besoins de limitation des *GES*, et en reconnaissance du rôle de la diversité, de la composition et de la structure forestière pour la produtivité et le fonctionnement de l'écosystème [@Begon2006].
Les pratiques de gestion sylvicoles actuelles sont calibrées pour maintenir un couvert forestier et un stock de biomasse de sous-bois déterminés, ce que leur confère la définition d' "exploitation durable" [@ITTO2005].
L'impact de l'exploitation forestière, adoptée aujourd'hui dans de nombreux pays, demeure controversé à propos du maintient de la biodiversité, spécifiquement sur le long terme.
 et plus spécifiquement le rôle des différents paramètres de l'exploitation tels que la densité d'exploitation, le diamètre minimal de coupe, ou la durée des rotations.

Le recul des 30 ans de suivi de Paracou donne une vision à long terme de la réponse des communautés à l'exploitation et permettent de discuter de points d'amélioration pour les pratiques d'exploitation sélective durable.

Ces espèces présentent également une hauteur et un diamètre maximums faibles, ce qui amplifie les changements de structure générés par les pertubations et modifie la valeur économique du peuplement [@Rutishauser2016].

### Quels critères de restauration?

Dans la perspective d'une exploitation soutenable à long terme, les critères d'évaluation de la durabilité doivent être discutés selon les objectifs de l'exploitation, qui ne sont plus uniquement le maintien du stock exploitable mais également des services et processus écosystémiques [@ITTO2005;@Barlow2018].

Les trajectoires de Paracou ont montré la résilience taxonomique et fonctionnelle des communautés, mais ont également mis en évidence la durée de cette restauration, toujours inachevée après 30 ans.
Dans le contexte de l'exploitation forestière cette durée implique des cycles de rotation plus longs que ceux éprouvés et validés pour d'autres bassins forestiers tropicaux, notamment en Afrique [@Durrieu1998].

Le recul des 30 ans d'inventaire à Paracou a démontré une réponse complexe de la diversité et de la composition taxonomique des communautés après exploitation.
Spécifiquement, les changements de composition taxonomique relèvent de processus aléatoires s'avérant difficiles à anticiper et pouvant n'être visibles qu'à long terme.
les conséquences de tels changements de composition taxonomiques peuvent cependant être non négligeables, entraînant par exemple la disparition d'espèces clé pour la faune ou la flore ou un blocage de succession modifiant durablement l'écosystème [@Diaz2005].
Compte tenu de la complexité de la réponse taxonomique, il est a mon sens recommandé d'une part de garder à l'esprit la possibilité de conséquences inattendues, d'autre part d'adopter un principe de précaution en favorisant la conservation des communautés par défaut, et enfin de poursuivre la recherche d'amélioration de la gestion forestière et des moyens (de mesure, de surveillance ou de modélisation) d'estimation de la restauration. 

L'analyse des trajectoires a montré le rôle central de la redondance fonctionnelle, qui appréhende la restauration de la composition taxonomique et de la résilience.
Une restauration inachevée de la redondance fonctionnelle implique, après plusieurs rotations, un risque élevé de voir dispaître localement les espèces les moins fréquentes et de rendre les communautés de plus en plus sensibles à la perturbation.
Nous proposons en conséquence la mesure de redondance fonctionnelle dans l'espace fonctionnel initial d'avant perturbation comme critère de restauration de l'écosystème, en plus des indicateurs fonctionnels actuels (*i.e.* la hauteur maximale, la vitesse de croissance ou la biomasse aérienne totale, etc) [@Sist2015].

### Choix des traits et limites de l'approche fonctionnelle

La diversité, de la composition et de la redondance fonctionnelle des communautés sont le lien le plus direct pour appréhender le fonctionnement et le maintien des écosystèmes [@Violle2007b;@Kunstler2016].
Ces conclusions concernent des mesures fonctionnelles basées sur des traits fonctionnels clés, représentatifs de l'écologie, de la croissance et dans une certaine mesure des performances de reproduction des espèces.
Comme tout jeu de traits fonctionnels, ce choix n'est cependant pas exhaustif du fonctionnement des espèces et les traits considérés ont été choisis pour appréhender surtout la productivité et la stratégie d'acquisition et d'utilisation des ressources des espèces.
Nous avons cependant pu souligner l'importance de la banque de graines pour la réponse des communautés et le rôle de sa diversité et de sa composition pour la consruction de la commmunauté après perturbation.
La constitution de la banque de graines dépend largement des traits de dispersion, de dormance et de germination des espèces, qu'il serait judicieux de considérer pour mieux anticiper le devenir des communautés perturbées [@Verdu2005;@Schleuning2016;@Yguel_inprep.].

## Vers l'intégration des trajectoires de biodiversité aux modèles de dynamique forestière

La modélisation est un outil qui simplifie les systèmes complexes en les limitant aux processus étudiés.
La modélisation revient d'une part à synthétiser les données et les connaissances du système puis à les extrapoler à des systèmes différents ou à d'autres échelles spatiales ou temporelles.
La modélisation est largement utilisée en écologie des forêts tropicales d'une part pour comprendre les processus, les lois et les déterminants de la dynamique forestière et d'autre part pour prédire la trajectoire des communautés dans le temps et leur réponse aux perturbations.
La modélisation des forêts tropicales a été largement développée pour l'étude de la structure forestière (hauteur et diamètre des arbres, densité du peuplement, biomasse, etc), des flux d'eau, de gaz ou de nutriments, ou encore de la distribution spatiale des espèces [@Piponiot2016;@Rutishauser2016;@Grimm2017].
Ces modèles sont largement utilisés pour anticiper la réponse des forêts aux changements climatiques et d'usage des terres d'une part, et pour calibrer la gestion forestière en vue des objectifs de l'exploitation [@Gourlet-Fleury2005].
Modéliser la diversité des forêts tropicales en revanche reste difficile, bien que cela soit indispensable compte tenu de son rôle pour le fonctionnements et les services écosystémiques. 
La grande diversité des forêts rend une approche espèce-spécifique difficile voire impossible et impose une approche à l'échelle des communautés.
Les forêts correspondent alors à une mosaïque de patch aux caractéristiques environnementales biotiques et abiotiques déterminées (richesse spécifique, traits fonctionnels moyens, densité d'arbres, intensité de la perturbation et temps écoulé depuis, etc) [@Porte2002].

Dans cette thèse nous avons synthétisé les informations des 30 ans de suivi de la réponse des communautés de Paracou après perturbation et en avons proposé une interprétation des processus sous-jacents et de la restauration.
Ce travail ouvre la voie à la modélisation de la biodiversité en forêt tropicale, que nous proposons d'envisager selon les deux perspectives empirique et mécaniste. 
L'approche empirique basée sur l'analyse statistique des trajectoires par des modèles mixtes permettrait de représenter les lois régissant la réponse de la diversité aux perturbations sans y expliciter les processus sous-jacents.
L'approche mécaniste basée sur des processus identifiés, spécifiquement le recrutement et la mortalité, permettrait de simuler la dynamique de différentes communautés.

### Modèle empirique: prédire la diversité en fonction de l'intensité d'exploitation

Les trajectoires de Paracou ont mis en évidence les corrélations au cours du temps entre l'intensité de la perturbation et la diversité fonctionnelle et taxonomique des communautés du temps écoulé depuis la perturbation et de son intensité.
Ces corrélations pourraient être formalisées par une modélisation empirique statistique prédisant la variation de diversité taxonomique des communautés en fonction du temps et de l'intensité de la perturbation (en % de biomasse perdue). 
Une telle relation entre intensité d'exploitation et diversité au cours du temps permettrait de mieux planifier la gestion forestière en fonction des niveaux de diversité attendus.

Spécifiquement, nous avons pensé ajuster des modèles mixtes aux trajectoires de diversité et de divergence de composition.
Les modèles mixtes sont largement utilisés dans l'étude de données "longitudinales", *i.e.* des mesures répétées dans le temps sur un même objet, comme c'est le cas des mesures de dynamique étudiées ici.
Ces modèles tiennent compte des corrélations entre mesures successives en associant une effet aléatoire commun aux mesures d'une même communauté.

### Modèle mécaniste: simuler les trajectoires après perturbation

Les trajectoires de paracou ont mis en évidence la succession des processus de recrutement déterministes ou stochastiques déterminant la réponse des communautés après perturbation.
La connaissance de ces processus inspire la construction de modèles mécanismes simulant explicitement la réponse des communautés aux perturbations.

Dans un premier temps, nous avons abordé la modélisation mécaniste en assimilant les trajectoires des communautés recrutées après perturbation à des courbes d'accumulation.
Les courbes d'accumulation représentent usuellement le nombre d'espèces découvertes en fonction de l'effort d'échantillonnage dans l'espace [@Gotelli2001].
Ces courbes se déclinent en courbes de raréfaction lissées, représentant le nombre moyen d'espèces rencontrées pour chaque sous-échantillonnage d'une communauté donnée selon des effectifs de taille variable [@Ugland2003].
Les courbes de raréfaction sont construites en considérant la richesse comme une variable aléatoire, dont l'espérance est estimée théoriquement à partir de la taille de la communauté initiale et la probabilité de tirage de chacune des espèces.
Nos essais ont cependant montré que les trajectoires du recrutement observées ne correspondaient à aucune courbe d'accumulation.
Dans le cas de perturbations peu intenses, comme à Paracou, les communautés après exploitation sont constituées à la fois des arbres survivants d'avant perturbation et des arbres recrutés par la suite.
La communauté des recrutés de même combine d'une part les recrutés issus des processus de recrutement de forêt mature (qui reflétent la composition et la diversité de la communauté initiale) et d'autre part les recrutés issus des processus de recrutement spécifiques à la perturbation (qui reflétent la composition et la diversité des espèces pionnières).
Les trajectoires du recrutement combinent deux communautés de survivants et de pionnières, et ne peuvent s'apparenter à une courbe de raréfaction qui concerne une unique communauté.

Notre étude a cependant montré que l'intensité de perturbation déterminait l'importance relative d'une part de ces deux communautés de survivants et de pionnières, et d'autre part l'importance des arbres recrutés par les processus stochastiques propres aux communautés matures, par rapport aux pionnières recrutées par les processus déterministes propres aux perturbations.
Partant de là, la réponse des communautés aux perturbations pourrait être modilisée par deux tirages aléatoires dans la population pré-exploitation d'une part et dans la population des espèces spécifiquement pionnières d'autre part.
L'enjeu sera au préalable de déterminer la pondération des tirages au cours du temps, par exemple grâce à une analyse de la variance tenant compte de la diversité apportées par communautés pionnières et d'avant exploitation.
De tels modèles pourraient d'une part être intégrés aux modèles de dynamique forestière existants et d'autre part d'élucider la réponse des communautés à des perturbations répétées, comme c'est le cas pour l'exploitation forestière [@Dufour2012].


