--- 
title: "Trajectoires de biodiversité en forêt tropicale exploitée"
author: "Ariane Mirabel"
date: "`r Sys.Date()`"
output: pdf_book
biblio-style: authoryear-ibid
bibliography:
- packages.bib
- 01ref-IntroG.bib
- 02ref-chap2Incert.bib
- 05ref-CclG.bib
cite-style: verbose-inote
classoption:
- extrafontsizes
- onecolumn
- openright
colorlinks: yes
abstract: |
  To be coming
description: "Manuscrit de thèse"
documentclass: memoir
fig_crop: yes
fontsize: 11pt
fourthpagefontsize: normalsize
graphics: yes
keywords:
- Biodiversity
- Neotropical forests
- Perturbation
- Communities Ecology
- Dynamic trajectories
- Resilience
lang: fr
link-citations: yes
mots-cles:
- Biodiversite
- Forets Neotropicales
- Perturbation
- Ecologie des Communautes
- Trajectoires dynamiques
- Resilience
otherlangs:
- en-US
- en-GB
- fr
biblatexoptions:
- backend=bibtex
- citestyle=verbose-inote
- isbn=false
- backref=true
- giveninits=true
- uniquename=init
- maxcitenames=2
- maxbibnames=150
- sorting=nyt
- sortcites=false
papersize: A4
resume: |
  La biodiversité des forêts, dans les arbres sont les éléments essentiels, est garante de leur fonctionnement, de leur résilience et des biens et services environnementaux, sociaux et économiques qu'elles rendent. Dans le contexte des changements actuels l'avenir des forêts est incertain, en particulier sous les tropiques où les forêts, qui accueillent la majeure partie de la biodiversité terrestre, sont les plus menacées.
  Comprendre le fonctionnement des écosystèmes forestiers pour anticiper leur réponse aux changements actuels et ajuster leur gestion durable à long terme est aujourd'hui un enjeu incontournable. Dans cet objectif, cette thèse cherche à expliciter la réponse des forêts tropicales dans le contexte de changements actuel, à en comprendre les processus sous-jacents, et à en discuter les perspectives pour le maintien des forêts et de leur fonctionnement. Nous proposons une analyse de la réponse des forêts tropicales aux perturbations à partir des trajectoires de diversité et de composition suivies pendant 30 ans après un gradient de perturbation par les parcelles du dispositif de Paracou en Guyane française.
  Dans un premier temps nous avons établi un estimateur de la diversité tenant compte des incertitudes de détermination inhérentes aux inventaires forestiers. Cet estimateur a été appliqué d'une part au contexte de l'exploitation forestière pour proposer une méthode d'inventaire optimisée vis à vis du coût (humain et temporel) des estimateurs et de leur précision. D'autre part il a été appliqué au contexte expérimental tel que celui de Paracou, et sera appliqué par la suite au tracé des trajectoires de diversité et de composition.
  Dans un deuxième temps nous avons analysé les trajectoires de diversité et de composition taxonomique et fonctionnelle des communautés après perturbation, à partir du suivi des parcelles de Paracou et d'un large jeu de données fonctionnel comprenant des traits des feuilles, du bois et des traits d'histoire de vie. Ces trajectoires ont montré la convergence fonctionnelle des communautés, illustrant une réponse commune régie par des mécanismes déterministes de sélection, et leur divergence taxonomique, illustrant le maintien de leurs différences de composition taxonomique régi par de sprocessus aléatoires de limites de dispersion. Les trajectoires de diversité ont par ailleurs validé la théories des perturbations intermédiaires au regard de la diversité taxonomique, maximisée après une perturbation d'intensité moyenne. L'impact des perturbations sur la diversité fonctionnelle s'est en revanche montré atténué par la redondance fonctionnelle importante des communautés, impliquant une augmentation de la diversité fonctionnelle quelle que soit l'intensité de la perturbation mais un temps de restauration long de plusieurs décennies.
  Enfin l'anaylse plus précise des trajectoires du recrutement ont montré une succession déterministe des communautés, similaire aux modèles de succession reconnus en forêt tempérée, régie par l'émergence de processus de sélection fonctionnelle balancant processus stochastiques de recrutement inhérents aux communautés matures. Cette succession a confirmé la résilience du fonctionnement et des charactéristiques taxonomiques et fonctionnelles des communautés, mais démontre la diminution de la résilience des communautés et interroge sur la possibilité d'une exploitation répétée et durable.
site: bookdown::bookdown_site
PhD-HDR:
  DIS: ST
  DocType: PhD
  ED: UG
  Ets: UG
  defence-date: 1er janvier 2018
  jury1:
    category: judge
    name: Prenom NomJury1
    other: Membre du Jury
    status: Professeur d'Universite
  jury2:
    category: judge
    name: Prenom NomJury2
    other: Membre du Jury
    status: Professeur d'Universite
  jury3:
    category: judge
    name: Prenom NomJury3
    other: Membre du Jury
    status: Professeur d'Universite
  jury4:
    category: judge
    name: Prenom NomJury4
    other: Membre du Jury
    status: Professeur d'Universite
  jury5:
    category: judge
    name: Prenom NomJury5
    other: Membre du Jury
    status: Professeur d'Universite
  jury6:
    category: judge
    name: Prenom NomJury6
    other: Membre du Jury
    status: Professeur d'Universite
  jury7:
    category: judge
    name: Prenom NomJury7
    other: Membre du Jury
    status: Professeur d'Universite
  lab: Ecologie des forets de Guyane
  njudge: 7
  speciality: Ecologie
toc-depth: 3
preamble: >
  \usepackage{textcomp}
  \DeclareUnicodeCharacter{B0}{\textdegree}
  \usepackage{tabu}
  \usepackage{caption}
  \captionsetup{justification = justified}
  \renewenvironment{table}{\begin{table*}}{\end{table*}\ignorespacesafterend}
  \hyphenation{bio-di-ver-si-ty sap-lings}
  \usepackage{floatrow}
  \floatsetup[widefigure]{margins=hangright,capposition=beside,
  capbesideposition={bottom, right},floatwidth=\textwidth}ASC
---

# Installation of packages if necessary and loading

Placeholder



<!--chapter:end:index.Rmd-->


# Introduction générale

Placeholder


## Les forêts tropicales, au coeur des enjeux actuels
## Exploitation et conservation des forêts tropicales
## Diversité et assemblage des communautés
### Succession, mortalité et recrutement: supports de la trajectoire des communautés
### Les règles d'assemblage des communautés
## Comment mesurer la diversité biologique ?
### Composition et dissimilarité entre communautés
### Assemblage et structure des communautés {#AbundanceDistribution}
### Les composantes de la diversité
### Résolution du biais d'échantillonnage
### Diversité fonctionnelle
## La Guyane Française et l'exemple de la station de Paracou
### Le contexte Guyanais
### Paracou, plus de 30 de suivi de la forêt Amazonienne
### Méthodes d'inventaires
## Problématique et plan de la thèse

<!--chapter:end:01-IntroductionGenerale.Rmd-->


# Article 1 : Des inventaires forestiers aux trajectoires de diversité: le problème universel de l'incertitude

Placeholder


## Noms vernaculaires et propagation des incertitudes taxonomiques
## Article 1 _ Inescapable Taxonomists: Workable Biodiversity Management Must Base on a Minimum Field Work
## La recherche et les suivis à long terme: application de la méthode de propagation aux inventaires de Paracou
### Profils d'incertitude taxonomique
### Cas particulier de Paracou

<!--chapter:end:02-IncertitudeTaxonomique.Rmd-->

# Article 2: trajectoires de diversité des parcelles

L'immense biodiversité des forêts tropicales est supposée déterminée et maintenue par un régime de perturbations régulier, comme l'illustre la théoriqe des perturbations intermédiaires.
Cette théorie suppose une diversité maximale des communautés pour un régime de perturbation moyen, mais elle reste débattue dans le cas des forêts tropicales, et cette controverse conduit à questionner la résilience des communautés après perturbation.

Nous étudions dans ce chapitre les trajectoires de diversité et de composition des communautés au cours des 30 années suivant un gradient de perturbation (10 à 60% de biomasse prélevée).
Nous avons analysé les trajectoires de composition, de richesse et de redondance taxonomique et fonctionnelle, en considérant 7 traits fonctionnels des feuilles, du bois et d'histoire de vie.

Les trajectoires de diversité ont mis en évidence une réponse taxonomique et fonctionnelle cyclique après perturbation, conduisant à la restauration des charactéristiques d'avant perturbation.
Les différentes trajectoires ont montré d'une part la divergence taxonomique des communautés, maintenant leurs différences de composition après exploitation du fait des limites de dispersion des espèces, et d'autre part leur convergence fonctionnelle,révélant une réponse commune régie par des processu de sélection fonctionnels.
La théorie des perturbations intermédiaires a pu représenter correctement l'impact des perturbations sur la diversité taxonomique, dont l'augmentation est positivement corrélé à l'intensité de la perturbation jusqu'à un ertain seuil. 
En revanche la sélection d'espèces fonctionnellement différentes augmentait la diversité fonctionnelle après perturbation quelle qu'en soit l'intensité, l'impact négatif de la perturbation étant atténué par l'importante redondance fonctionnelle des communautés.
Bien qu'effective, la restauration des charactéristiques taxonomiques et fonctionnelles des communautés restait inachevée après 30 ans, suggérant un temps de restauration long de plusieurs décenies d'autant plus difficile à estimer que la restauration de la redondance fonctionnelle, déterminante de la résilience des communautés, s'est montrée ralentir au cours du temps.


<!--chapter:end:03-TrajectoiresDeDiversité.Rmd-->

# Article 3: Analyse du recrutement, support de la trajectoire des communautés

La réponse des communautés aux perturbations est déterminée par les trajetoires du recrutment, reconnu pour suivre une succession déterministe régie après perturbation.
Ceci reste cependant à tester dans le cas des forêts tropicales, dont l'immense biodiversité pourrait atténuer les processus déterministes, et dans le cas particulier de perturbations relativement peu intenses en comparaison des coupes rases ou de la secondarisation pour lesquels ont été observés les modèles de succession classique.  
Nous étudions dans ce chapitre les trajectoires de diversité taxonomique et fonctionnelle du recrutement après exploitation pour (i) clarifier l'importance respective des processus stochastiques et déterministes au cours de la succession  des processus écologiques et (ii) déterminer la résilience et la durée de restauration des processus démographiques après exploitation.

Nous avons tracé et comparé à des odèles nuls stochastiques les trajectoires de diversité et d'équitabilité taxonomique, de renouvellement des espèces par rapport à la communauté avant perturbation, et de diversité fonctionnelle.

Nous avons identifié trois phases de recrutement après perturbation, définies par l'équilibre entre les processus déterministes et stochastiques impliqués.
Dans un premier temps les trajectoires sont portées par la croissance de juvéniles recrutés aléatoirement dans la communauté d'avant exploitation.
Dans un deuxième temps les trajectoires reposent sur les "recrutés vrais" issus de la banque de graines et tributaires de processus d'exclusion pour la lumière favorisant les espèces héliophiles à croissance rapide.
La troisième et dernière phase des trajectoires correspond au retour progressif vers un recrutement aléatoire restorant la structure, la composition taxonomique et le fonctionnement de la communauté initiale. 
Si le fontionnement du recrutement a été rapidement retrouvé, la restoration taxonomique s'est montrée longue, ce qui interroge l'intégralité de la résilience et malgré la réelle restoration de la diversité et de la composition initiale, Les différentes trajectoires ont par ailleurs confirmé une restoration de la diversité fonctionnelle rapide mais plus lente de la composition et de la diversité taxonomiques.

La trajectoire des communautés après perturbation résulte de la combinaison des processus stochastiques, majeurs avant perturbation et progressivement restorés par la suite, et de processus déterministes d'exclusion compétitive favorisant les espèces héliophiles et à croissance rapide.
La résilience de la composition et la diversité taxonomiques et fonctionnelles du recrutement a été confirmée mais longue de plusieurs décennies, et confirme le risque de trajectoires différentes dans le cas de perturbations répétées.

  

<!--chapter:end:04-RecruitmentDynamics.Rmd-->

# Conclusion et perspectives

La diversité des communautés d'arbres tient un rôle central pour le fonctionnement et le maintien des écosystèmes forestiers et des services qu'ils rendent [@Tilman2014].
Expliciter la réponse de cette diversité est incontournable pour anticiper le devenir des forêts dans le contexte actuel, en comprendre les mécanismes et les facteurs déterminants et adapter leur gestion et leur conservation [@Barlow2018]. 
Nous proposons ici une étude exhaustive de la réponse taxonomique et fonctionnelle d'une communauté de forêt Néotropicale à un gradient de perturbation.

De telles études de la diversité des forêts tropicales sont souvent limitées par la précision des inventaires botaniques et des bases de données fonctionnelles du fait de leur coût financier et humain.
Le premier travail de cette thèse a été de développer des estimateurs de diversité taxonomique et fonctionnelle palliant les incertitudes inhérentes aux bases de données botaniques fonctionnelles.
Ces estimateurs, testés et calibrés à partir des inventaires réels, ont permis dans un deuxième temps le suivi exhaustif des trajectoires de diversité taxonomiques et fonctionnelles des communautés et du recrutement au cours des 30 ans après perturbations. 
Ces trajectoires ont permis d'expliciter la réponse des communautés aux perturbations, les processus écologiques sous-jacents et les aspects taxonomiques et fonctionnels de leur résilience.
Ces résultats conduisent à différentes perspectives d'une part pour la gestion et la conservation durables des forêts tropicales et d'autre part pour développer la modélisation de la diversité des communautés.

## La diversité des communautés, entre déterminisme et stochasticité

Comprendre la réponse des communautés aux perturbation revient à élucider les processus régissant la coexistence des espèces et leur assemblage en communautés.
En forêt tropicale il est encore largement débattu de la prépondérance des processus stochastiques, supposée par la théorie neutre prédisant un assemblage aléatoire des espèces, par rapport à des processus déterministes favorisant les espèces selon leurs caractéristiques fonctionnelles, supposés par la théorie des perturbations intermédiaires.
La prépondérance de processus stochastique implique que l'assemblage des communautés varie de façon aléatoire suivant des contingences historiques (ordre d'arrivée des espèces, mortalité aléatoire, activité anthropique) ou géographiques (limitation de la dispersion).
La prépondérance de processus déterministes à l'inverse suppose la convergence des communautés vers la composition et la diversité d'avant perturbation, déterminées par les caractéristiques environnementales.
Les deux théories neutres et déterministes ne se sont pas incompatibles et se sont montrées pertinentes dans différents cas de figure.
@Chave2004 propose une théorie intégrative expliquant la diversité et la composition des communautés par la combinaison variable dans le temps et l'espace des processus stochastiques et déterministes.

### Un modèle de succession déterministe

Les trajectoires de diversité du recrutement après perturbation ont permis de distinguer trois phases de succession correspondant à des processus distincts.
Quelle que soit l'intensité de la pertubation, la trajectoire des communutés est déterminée par (i) le recrutement de plantules déjà établies bénéficiant de l'espace environnemental rendu disponible par la perturbation, (ii) la favorisation de pionnières et d'héliophiles aux stratégies d'acquisition de la lumière les plus efficaces, et (iii) le retour progressif aux processus de recrutement initiaux.

Cette succession montre que des processus stochastiques, neutres, assurent le maintien de la diversité des communautés tandis que les perturbations correspondent à l'émergence de processus déterministes changeant significativement la diversité et la composition du recrutement.
Les processus de recrutement s'avèrent restaurés après quelques décennies mais à l'échelle de la communauté l'impact des perturbations est de plus long terme et largement hétérogène, selon l'intensité de la perturbation et la composition initiale des communautés.

### Une succession fonctionnelle déterministe

La réponse des communautés dépend des changements biotiques et abiotiques qui accélèrent la croissance des arbres et augmentent le nombre de recrutés.
Après perturbation l'émergence de processus déterministes de sélection des espèces définit les trajectoires de diversité et de composition fonctionnelle des communautés, et par extension leur fonctionnement [@Violle2007b;@Baraloto2012a].
La perturbation, matérialisée par la mortalité d'une partie de la communauté, modifie en elle-même la distribution d'âge des arbres, la structure de hauteur et de diamètre des communautés et leur environnement abiotique (lumière, flux d'eau et de nutriments) [@Gourlet-Fleury2000;@Putz2012;@Piponiot2016;@Rutishauser2016].
Si le taux de mortalité est plus élevé après perturbation, la composition et la diversité des arbres survivants a montré refléter celles d'avant perturbation [@Herault2018].
Les changements de diversité et de composition fonctionnelle des communautés relèvent donc du recrutement d'espèces dont la stratégie fonctionnelle diffère des traits moyens de la communauté.

Dans un premier temps les juvéniles déjà en place avant perturbation réagissent aux changements environnementaux sans être soumis à des processus de sélection et on suppose que leur recrutement ne modifie pas le fonctionnement de l'écosystème [@Denslow2000;@Herault2010]. 
Dans un deuxième temps les arbres recrutés, issus de la germination des graines de la banque du sol, sont soumis à des processus d'exclusion compétitive basés sur leur stratégie d'acquisition de la lumière.
Les individus recrutés à ce moment, qui consituent l'essentiel du recrutement après perturbation [@Lawton1988], correspondent majoritairement à des espèces à croissance rapide, au détriment d'espèces tolérantes à l'ombre inféodées aux forêts non perturbées.
Ces espèces pionnières sont peu diversifiées, mais leur dissimilarité par rapport à la communauté d'avant perturbation augmente malgré tout la diversité fonctionnelle.
Au delà d'un seuil d'intensité de perturbation (plus de 25% de biomasse initiale perdue)  correspond nous avons établi que quelques espèces très pionnières dominaient largement cette seconde phase de recrutement (par exemple *Cecropia spp*, *Pourouma spp.* ou *Vismia spp.*) [@Guitet2018].
A ce moment, les stratégies fonctionnelles très héliophiles deviennent dominantes et on s'attend à d'importantes modifications du fonctionnement des communautés. 
Ces stratégies "acquisitives" vis à vis des ressources du milieu correspondent à des espèces à courte durée de vie et aux tissus peu denses, impliquant un turnover rapide du carbone (peu stocké dans la biomasse végétale) et des nutriments (rapidement dégradés dans la litière) [@Falster2011].
Ces espèces présentent également une hauteur et un diamètre maximums faibles, ce qui amplifie les changements de structure générés par les pertubations et modifie la valeur économique du peuplement [@Rutishauser2016].
Au cours du temps, la croissance du premier pool de recrutés entraîne des modifications de structure et de l'environnement abiotique de la communauté (fermeture de la canopée, rétablissement de la compétition, etc.) et les espèces pionnières sont moins favorisées par rapport aux espèces d'avant perturbation [@Denslow2000].
Le recrutement correspond ainsi dans un troisième temps à la restauration des caractéristiques fonctionnelles d'avant perturbation,déterminant une trajectoire cyclique fonctionnelle cyclique. 
L'implication d'un pool unique de pionnières rend la trajectoire après perturbation commune à toutes les communautés.
Malgré des modifications fonctionnelles plus importantes au delà du seuil d'intensité, les trajectoires suivant les pertubations les plus intenses rejoignent la trajectoire commune et la résilience fonctionnelle des communautés n'est pas remise en cause.

### Les trajectoires taxonomique

A l'échelle de la communauté, l'exemple de Paracou a démontré l'hétérogeneité de la réponse des communautés en fonction de l'intensité de la perturbation et de la composition initiale des communautés.
En deça d'un seuil d'intensité (environ 25% de biomasse initiale perdue) le pool des espèces pionnières favorisées après perturbation, auparavant absentes ou peu abondantes, augmente la richesse et l'équitabilité des communautés.
La diversité taxonomique augmente ainsi pendant les deux premières phases de la succession, jusqu'au retour progresssif des processus de recrutement initiaux.
Conformément aux hypothèses de @Connell1978 sur la théorie des perturbations intermédiaires, la diversité des communautés est maximale pour un régime de perturbations régulières d'intensité moyenne.
Un tel régime entraîne de façon déterministe la coexistence d'espèces pionnières, mobilisant efficacement les ressources rendues disponibles par la perturbation, et d'espèces de succession tardives (dont la diversité est maintenue malgré la perturbation), plus compétitives et qui exclueront les pionnères par la suite [@Molino2001:@Guitet2018].
Au delà d'un seuil d'intensité en revanche la favorisation d'espèces nouvelles ou peu communes ne compense pas les disparitions dues à la perturbation.
Les espèces pionnières deviennent alors dominantes et l'équitabilité des communautés est largement et durablement augmentée.

Les espèces pionnières recrutées sont par ailleurs identiques quelles que soient la communauté initiale et l'intensité de la perturbation.
La composition des communautés est effectée de façon pour toutes les communautés et leurs différences de compositions initiales sont maintenues et les trajectoires des communautés divergent dans l'espace taxonomique. 
Peu d'espèces non présentes initialement s'installent après perturbation malgré l'espace libéré, une restriction probablement due aux limites de dispersion identifiées pour beaucoup d'espèces de forêt tropicale [@Svenning2005].
Conformément à l'esprit de la théorie neutre la composition taxonomique des communautés relève donc de la contingence historique, *i.e.* du hasard de l'arrivée et de l'installation des espèces, plus que de processus de sélection déterministes [@Hubbell2001].

Les communautés convergent donc dans l'espace fonctionnel, comme on l'a vu, tandis qu'elles divergent dans l'espace taxonomique [@Fukami2005].
Cette dichotomie entre trajectoires de composition taxonomique et fonctionnelle s'explique par la redondance fonctionnelle élevée des forêts tropicales [@Bellwood2006].
Cette redondance fonctionnelle élevée indique que de nombreuses espèces partagent les mêmes traits et stratégies fonctionnelles. 
Cela implique d'une part que le fonctionnement et la réponse fonctionnelle aux perturbations soit similaires entre communautés malgré leurs différences de composition taxonomique, et d'autre part que l'impact fonctionnel des perturbations soit atténué car le rôle d'une espèce disparue de la communauté sera assuré par une espèce redondante [@Carmona2016].
Par ailleurs, une redondance fonctionnelle élevée implique une compétition importante entre espèces redondantes, ce qui rend la restauration taxonomique des communautés lente et dépendante du hasard de recrutement des espèces.
La population des espèces rares en particulier, qui disparaissent de la communauté plus fréquemment après perturbation du fait de leur effectif réduit, s'avère longue à restaurer.
Selon la principe de "lottery recruitment", les premières espèces recrutées s'établiront dans la communauté tandis que celles, par hasard, recrutées plus tard seront en compétition ave les premières et s'établiront plus difficilement [@Busing2002].
La restauration de la composition taxonomique et de la redondance fonctionnelle initiales est longue et difficile à anticiper.
La redondance fonctionnelle garantie la résilience des communautés et atténue l'impact des perturbations sur le fonctionnement des écosystèmes, plusieurs espèces pouvant assurer le même rôle, mais elle reste impactée plusieurs décennies après pertubation.
On s'attend à ce que la réponse des communautés après de nouvelles pertubations soit assez différente, et notamment à ce que le fonctionnement finisse par être modifié sur le long terme et la redondance fonctionnelle n'est pas restaurée.
La restauration lente des espèces rares quand à elle accroît le risque de voir certaines espèces disparaître localement, et de voir la richesse taxonomique décliner petit à petit.

## Vers une gestion plus durable intégrant la préservation de la biodiversité

L'exploitation sélective est considérée comme étant l'une des pratiques d'exploitation les moins néfastes pour préserver l'intégrité et le fonctionnement des forêts tout en dégageant des bénéfices économiques et sociaux significatifs [@Chaudhary2016].
L'exploitation sélective a été adoptée dernièrement par de nombreux pays, suite à des réorganisations de l'économie locale, en réponse aux besoins de limitation des *GES*, et en reconnaissance du rôle de la diversité, de la composition et de la structure forestière pour la produtivité et le fonctionnement de l'écosystème [@Begon2006].
Les pratiques de gestion sylvicoles actuelles sont calibrées pour maintenir un couvert forestier et un stock de biomasse de sous-bois déterminés, ce que leur confère la définition d' "exploitation durable" [@ITTO2005].
L'impact de l'exploitation forestière, adoptée aujourd'hui dans de nombreux pays, demeure controversé à propos du maintient de la biodiversité, spécifiquement sur le long terme.
 et plus spécifiquement le rôle des différents paramètres de l'exploitation tels que la densité d'exploitation, le diamètre minimal de coupe, ou la durée des rotations.

Le recul des 30 ans de suivi de Paracou donne une vision à long terme de la réponse des communautés à l'exploitation et permettent de discuter de points d'amélioration pour les pratiques d'exploitation sélective durable.

### Quels critères de restauration?

Dans la perspective d'une exploitation soutenable à long terme, les critères d'évaluation de la durabilité doivent être discutés selon les objectifs de l'exploitation, qui ne sont plus uniquement le maintien du stock exploitable mais également des services et processus écosystémiques [@ITTO2005;@Barlow2018].

Les trajectoires de Paracou ont montré la résilience taxonomique et fonctionnelle des communautés, mais ont également mis en évidence la durée de cette restauration, toujours inachevée après 30 ans.
Dans le contexte de l'exploitation forestière cette durée implique des cycles de rotation plus longs que ceux éprouvés et validés pour d'autres bassins forestiers tropicaux, notamment en Afrique [@Durrieu1998].

Le recul des 30 ans d'inventaire à Paracou a démontré une réponse complexe de la diversité et de la composition taxonomique des communautés après exploitation.
Spécifiquement, les changements de composition taxonomique relèvent de processus aléatoires s'avérant difficiles à anticiper et pouvant n'être visibles qu'à long terme.
les conséquences de tels changements de composition taxonomiques peuvent cependant être non négligeables, entraînant par exemple la disparition d'espèces clé pour la faune ou la flore ou un blocage de succession modifiant durablement l'écosystème [@Diaz2005].
Compte tenu de la complexité de la réponse taxonomique, il est a mon sens recommandé d'une part de garder à l'esprit la possibilité de conséquences inattendues, d'autre part d'adopter un principe de précaution en favorisant la conservation des communautés par défaut, et enfin de poursuivre la recherche d'amélioration de la gestion forestière et des moyens (de mesure, de surveillance ou de modélisation) d'estimation de la restauration. 

L'analyse des trajectoires a montré le rôle central de la redondance fonctionnelle, qui appréhende la restauration de la composition taxonomique et de la résilience.
Une restauration inachevée de la redondance fonctionnelle implique, après plusieurs rotations, un risque élevé de voir dispaître localement les espèces les moins fréquentes et de rendre les communautés de plus en plus sensibles à la perturbation.
Nous proposons en conséquence la mesure de redondance fonctionnelle dans l'espace fonctionnel initial d'avant perturbation comme critère de restauration de l'écosystème, en plus des indicateurs fonctionnels actuels (*i.e.* la hauteur maximale, la vitesse de croissance ou la biomasse aérienne totale, etc) [@Sist2015].

### Choix des traits et limites de l'approche fonctionnelle

La diversité, de la composition et de la redondance fonctionnelle des communautés sont le lien le plus direct pour appréhender le fonctionnement et le maintien des écosystèmes [@Violle2007b;@Kunstler2016].
Ces conclusions concernent des mesures fonctionnelles basées sur des traits fonctionnels clés, représentatifs de l'écologie, de la croissance et dans une certaine mesure des performances de reproduction des espèces.
Comme tout jeu de traits fonctionnels, ce choix n'est cependant pas exhaustif du fonctionnement des espèces et les traits considérés ont été choisis pour appréhender surtout la productivité et la stratégie d'acquisition et d'utilisation des ressources des espèces.
Nous avons cependant pu souligner l'importance de la banque de graines pour la réponse des communautés et le rôle de sa diversité et de sa composition pour la consruction de la commmunauté après perturbation.
La constitution de la banque de graines dépend largement des traits de dispersion, de dormance et de germination des espèces, qu'il serait judicieux de considérer pour mieux anticiper le devenir des communautés perturbées [@Verdu2005;@Schleuning2016;@Yguel_inprep.].

## Vers l'intégration des trajectoires de biodiversité aux modèles de dynamique forestière

La modélisation est un outil qui simplifie les systèmes complexes en les limitant aux processus étudiés.
La modélisation revient d'une part à synthétiser les données et les connaissances du système puis à les extrapoler à des systèmes différents ou à d'autres échelles spatiales ou temporelles.
La modélisation est largement utilisée en écologie des forêts tropicales d'une part pour comprendre les processus, les lois et les déterminants de la dynamique forestière et d'autre part pour prédire la trajectoire des communautés dans le temps et leur réponse aux perturbations.
La modélisation des forêts tropicales a été largement développée pour l'étude de la structure forestière (hauteur et diamètre des arbres, densité du peuplement, biomasse, etc), des flux d'eau, de gaz ou de nutriments, ou encore de la distribution spatiale des espèces [@Piponiot2016;@Rutishauser2016;@Grimm2017].
Ces modèles sont largement utilisés pour anticiper la réponse des forêts aux changements climatiques et d'usage des terres d'une part, et pour calibrer la gestion forestière en vue des objectifs de l'exploitation [@Gourlet-Fleury2005].
Modéliser la diversité des forêts tropicales en revanche reste difficile, bien que cela soit indispensable compte tenu de son rôle pour le fonctionnements et les services écosystémiques. 
La grande diversité des forêts rend une approche espèce-spécifique difficile voire impossible et impose une approche à l'échelle des communautés.
Les forêts correspondent alors à une mosaïque de patch aux caractéristiques environnementales biotiques et abiotiques déterminées (richesse spécifique, traits fonctionnels moyens, densité d'arbres, intensité de la perturbation et temps écoulé depuis, etc) [@Porte2002].

Dans cette thèse nous avons synthétisé les informations des 30 ans de suivi de la réponse des communautés de Paracou après perturbation et en avons proposé une interprétation des processus sous-jacents et de la restauration.
Ce travail ouvre la voie à la modélisation de la biodiversité en forêt tropicale, que nous proposons d'envisager selon les deux perspectives empirique et mécaniste. 
L'approche empirique basée sur l'analyse statistique des trajectoires par des modèles mixtes permettrait de représenter les lois régissant la réponse de la diversité aux perturbations sans y expliciter les processus sous-jacents.
L'approche mécaniste basée sur des processus identifiés, spécifiquement le recrutement et la mortalité, permettrait de simuler la dynamique de différentes communautés.

### Modèle empirique: prédire la diversité en fonction de l'intensité d'exploitation

Les trajectoires de Paracou ont mis en évidence les corrélations au cours du temps entre l'intensité de la perturbation et la diversité fonctionnelle et taxonomique des communautés du temps écoulé depuis la perturbation et de son intensité.
Ces corrélations pourraient être formalisées par une modélisation empirique statistique prédisant la variation de diversité taxonomique des communautés en fonction du temps et de l'intensité de la perturbation (en % de biomasse perdue). 
Une telle relation entre intensité d'exploitation et diversité au cours du temps permettrait de mieux planifier la gestion forestière en fonction des niveaux de diversité attendus.

Spécifiquement, nous avons pensé ajuster des modèles mixtes aux trajectoires de diversité et de divergence de composition.
Les modèles mixtes sont largement utilisés dans l'étude de données "longitudinales", *i.e.* des mesures répétées dans le temps sur un même objet, comme c'est le cas des mesures de dynamique étudiées ici.
Ces modèles tiennent compte des corrélations entre mesures successives en associant une effet aléatoire commun aux mesures d'une même communauté.

### Modèle mécaniste: simuler les trajectoires après perturbation

Les trajectoires de paracou ont mis en évidence la succession des processus de recrutement déterministes ou stochastiques déterminant la réponse des communautés après perturbation.
La connaissance de ces processus inspire la construction de modèles mécanismes simulant explicitement la réponse des communautés aux perturbations.

Dans un premier temps, nous avons abordé la modélisation mécaniste en assimilant les trajectoires des communautés recrutées après perturbation à des courbes d'accumulation.
Les courbes d'accumulation représentent usuellement le nombre d'espèces découvertes en fonction de l'effort d'échantillonnage dans l'espace [@Gotelli2001].
Ces courbes se déclinent en courbes de raréfaction lissées, représentant le nombre moyen d'espèces rencontrées pour chaque sous-échantillonnage d'une communauté donnée selon des effectifs de taille variable [@Ugland2003].
Les courbes de raréfaction sont construites en considérant la richesse comme une variable aléatoire, dont l'espérance est estimée théoriquement à partir de la taille de la communauté initiale et la probabilité de tirage de chacune des espèces.
Nos essais ont cependant montré que les trajectoires du recrutement observées ne correspondaient à aucune courbe d'accumulation.
Dans le cas de perturbations peu intenses, comme à Paracou, les communautés après exploitation sont constituées à la fois des arbres survivants d'avant perturbation et des arbres recrutés par la suite.
La communauté des recrutés de même combine d'une part les recrutés issus des processus de recrutement de forêt mature (qui reflétent la composition et la diversité de la communauté initiale) et d'autre part les recrutés issus des processus de recrutement spécifiques à la perturbation (qui reflétent la composition et la diversité des espèces pionnières).
Les trajectoires du recrutement combinent deux communautés de survivants et de pionnières, et ne peuvent s'apparenter à une courbe de raréfaction qui concerne une unique communauté.

Notre étude a cependant montré que l'intensité de perturbation déterminait l'importance relative d'une part de ces deux communautés de survivants et de pionnières, et d'autre part l'importance des arbres recrutés par les processus stochastiques propres aux communautés matures, par rapport aux pionnières recrutées par les processus déterministes propres aux perturbations.
Partant de là, la réponse des communautés aux perturbations pourrait être modilisée par deux tirages aléatoires dans la population pré-exploitation d'une part et dans la population des espèces spécifiquement pionnières d'autre part.
L'enjeu sera au préalable de déterminer la pondération des tirages au cours du temps, par exemple grâce à une analyse de la variance tenant compte de la diversité apportées par communautés pionnières et d'avant exploitation.
De tels modèles pourraient d'une part être intégrés aux modèles de dynamique forestière existants et d'autre part d'élucider la réponse des communautés à des perturbations répétées, comme c'est le cas pour l'exploitation forestière [@Dufour2012].



<!--chapter:end:05-ConclusionPerspectives.Rmd-->

`r if (knitr:::is_html_output()) '# References {-}'`

<!--chapter:end:99-references.Rmd-->

